import { Component } from '@angular/core';
import {SaveData} from "./components/editor/editor.component";
import * as htmlToImage from "html-to-image";
import * as zlib from 'pako';
// import * as zlib from 'pako';

export type StorageSaveData = {
  terrain: string;
  group: string;
  expansion: string;
  tileId: string;
  data: SaveData[];
  guid: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public storageKey = 'tileCreatorData';
  public tileList:StorageSaveData[] = [];

  public exportImport: string = '';
  public defaultData: string = 'W3sidGVycmFpbiI6InN1YnRlcnJhaW4iLCJncm91cCI6ImNlbnRlciIsImV4cGFuc2lvbiI6ImNvcmUiLCJ0aWxlSWQiOiJDMSIsImd1aWQiOiI0RUMwQUJGRi00OUQzLTFGNjMtQkEwMi0wMEExMkYyM0ZDODciLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjYiLCJpY29uIjoicGFuZG9yYSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiJmb3VudGFpbi1vZi15b3V0aCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJ3YXJyaW9ycy10b21iIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MywiZW5lbXkiOiI3IiwiaWNvbiI6ImRyYWdvbi11dG9waWEiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo1LCJlbmVteSI6IjAiLCJpY29uIjoibXlzdGljYWwtZ2FyZGVuIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiI2IiwiaWNvbiI6InNocmluZS1nZXN0dXJlIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoic3VidGVycmFpbiIsImdyb3VwIjoiY2VudGVyIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IkMyIiwiZ3VpZCI6IjFCN0UwNERGLTY2MDEtRjJENS02Qzk3LUZGRjE0NjVCOTlERCIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiNiIsImljb24iOiJ0cmVlLW9mLWtub3dsZWRnZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiJzaHJpbmUtZ2VzdHVyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJteXN0aWNhbC1nYXJkZW4iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjciLCJpY29uIjoiZ3JhaWwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoidGVtcGxlIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiI2IiwiaWNvbiI6InBhbmRvcmEiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJsYXZhIiwiZ3JvdXAiOiJjZW50ZXIiLCJleHBhbnNpb24iOiJpbmZlcm5vIiwidGlsZUlkIjoiQzUiLCJndWlkIjoiNjQ0NDg4QjgtNEM3OC1BOUJGLTAzQkEtRkVERUE0QzRGRTE3IiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiI2IiwiaWNvbiI6InRyZWUtb2Yta25vd2xlZGdlIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIwIiwiaWNvbiI6IndhcnJpb3JzLXRvbWIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjciLCJpY29uIjoicmFuZG9tLXRvd24iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoidGVtcGxlIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiI2IiwiaWNvbiI6InN0YXJheGlzIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6InNhbmN0dWFyeSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6ImN1cnNlZCIsImdyb3VwIjoiZmFyIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IkYxIiwiZ3VpZCI6IkRCQjMzODc1LTNBNzgtOTYxNS03NERCLUU1OEQ5NjM1NzFGQSIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMyIsImljb24iOiJyYW5kb20tbmVjcm8iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoid2luZG1pbGwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIyIiwiaWNvbiI6InNrZWxldG9uIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6InRyYWRpbmdwb3N0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6InN0YWJsZXMiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJzdWJ0ZXJyYWluIiwiZ3JvdXAiOiJmYXIiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiRjIiLCJndWlkIjoiMjlDNjAwRjctNEMyRC00NDdBLTU1ODktRDVEQzg5QTFBQ0YxIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6InRyYWRpbmdwb3N0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIzIiwiaWNvbiI6InJhbmRvbS1kdW5nZW9uIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MiwiZW5lbXkiOiIwIiwiaWNvbiI6Im1hZ2ljc2hyaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MywiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiJmb3VudGFpbi1vZi15b3V0aCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMiIsImljb24iOiJza2VsZXRvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6ImdyYXNzIiwiZ3JvdXAiOiJmYXIiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiRjMiLCJndWlkIjoiMENDN0Q2Q0QtM0RDOS03MjExLUFFRTgtRDIwNjU2RUYyRkMwIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6IndhdGVyd2hlZWwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoibGVhcm5pbmctc3RvbmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjMiLCJpY29uIjoicmFuZG9tLXRvd24iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjIiLCJpY29uIjoic2tlbGV0b24iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoic3RhYmxlcyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJzdWJ0ZXJyYWluIiwiZ3JvdXAiOiJmYXIiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiRjUiLCJndWlkIjoiQTZGNkU1NTAtNkNDQy0zMTE0LTUzOTQtMUUxMTlFQTgwMUY4IiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIzIiwiaWNvbiI6ImdvbGRtaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIyIiwiaWNvbiI6Im15c3RpY2FsLWdhcmRlbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoib2JzZXJ2YXRvcnkiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo1LCJlbmVteSI6IjAiLCJpY29uIjoidHJhZGluZ3Bvc3QiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoibGVhcm5pbmctc3RvbmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJncmFzcyIsImdyb3VwIjoiZmFyIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IkY2IiwiZ3VpZCI6IjJDRkM4OEFBLUNCM0MtQjQ4RS0yMURELTQzMEJERTQyNjBFNiIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMiIsImljb24iOiJza2VsZXRvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiJ0cmFkaW5ncG9zdCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJ3YXRlcndoZWVsIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MywiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIwIiwiaWNvbiI6Im1hZ2ljc2hyaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMyIsImljb24iOiJnb2xkbWluZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6ImN1cnNlZCIsImdyb3VwIjoiZmFyIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IkY3IiwiZ3VpZCI6IkExN0RFMDlBLTRERjQtRjUxNi01RjFELTZGMEI1OTQ3QUEwNSIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMiIsImljb24iOiJjaGVzdCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJsZWFybmluZy1zdG9uZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjMsImVuZW15IjoiMCIsImljb24iOiJzaHJpbmUtZ2VzdHVyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo1LCJlbmVteSI6IjAiLCJpY29uIjoib2JzZXJ2YXRvcnkiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo2LCJlbmVteSI6IjMiLCJpY29uIjoiYWxjaGVtaXN0bGFiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoic3VidGVycmFpbiIsImdyb3VwIjoiZmFyIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IkY4IiwiZ3VpZCI6Ijk2RENGNTBELTQ1MUMtNzM3RS05QkYyLUJENjY3MTQ4QzlEOCIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMCIsImljb24iOiJzdGFibGVzIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJ0ZW1wbGUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjMiLCJpY29uIjoiZ2VtcG9uZCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiJ3aW5kbWlsbCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMiIsImljb24iOiJjaGVzdCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6InN3YW1wIiwiZ3JvdXAiOiJmYXIiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiRjE0IiwiZ3VpZCI6IjU0MkEyQzhELUQ2NUYtNTI2Ri03NDdBLUM1NTRCREYzQTE4NCIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMyIsImljb24iOiJnb2xkbWluZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiJ3aW5kbWlsbCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoic3RhYmxlcyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMiIsImljb24iOiJza2VsZXRvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMCIsImljb24iOiJjYW1wZmlyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6ImxhdmEiLCJncm91cCI6ImZhciIsImV4cGFuc2lvbiI6ImluZmVybm8iLCJ0aWxlSWQiOiJGMTYiLCJndWlkIjoiNzlCODk0ODgtRkZBMC1CRjA5LTY5RjYtNkFGREQxRjE4QkFEIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6Im1hZ2ljc2hyaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIzIiwiaWNvbiI6InJhbmRvbS10b3duIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MiwiZW5lbXkiOiIwIiwiaWNvbiI6ImxlYXJuaW5nLXN0b25lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MywiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMiIsImljb24iOiJza2VsZXRvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMCIsImljb24iOiJ3aW5kbWlsbCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6ImN1cnNlZCIsImdyb3VwIjoibmVhciIsImV4cGFuc2lvbiI6ImNvcmUiLCJ0aWxlSWQiOiJOMSIsImd1aWQiOiJDRTIxREJENC01Njg0LTNFOTUtMzExOC1GMDFBQkQxNjk5QTQiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoid2luZG1pbGwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjAiLCJpY29uIjoidHJlZS1vZi1rbm93bGVkZ2UiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjQiLCJpY29uIjoid2l0Y2hodXQiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjAiLCJpY29uIjoic2FuY3R1YXJ5IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6InRyYWRpbmdwb3N0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiI1IiwiaWNvbiI6ImdlbXBvbmQiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJjdXJzZWQiLCJncm91cCI6Im5lYXIiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiTjQiLCJndWlkIjoiQkZFMUQ0MjAtQ0RBRS0xOEJCLTI4OUUtOTM5QzRFMURGOEJDIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6IndhdGVyd2hlZWwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoibWFnaWNzcHJpbmciLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjQiLCJpY29uIjoic2hyaW5lLWdlc3R1cmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoib2JlbGlzayIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiNSIsImljb24iOiJnb2xkbWluZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiJ3YXJyaW9ycy10b21iIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoic3VidGVycmFpbiIsImdyb3VwIjoibmVhciIsImV4cGFuc2lvbiI6ImNvcmUiLCJ0aWxlSWQiOiJONSIsImd1aWQiOiI3MzI3NjdFMC0wMDM2LUU3Q0MtQzY4Qi0wRjBCMDk1RTFFQjQiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjAiLCJpY29uIjoic2hyaW5lLWdlc3R1cmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjUiLCJpY29uIjoiZ29sZG1pbmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjQiLCJpY29uIjoibWFnaWNzcHJpbmciLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoib2JlbGlzayIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiJ3YXJyaW9ycy10b21iIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6IndhdGVyd2hlZWwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJncmFzcyIsImdyb3VwIjoibmVhciIsImV4cGFuc2lvbiI6ImNvcmUiLCJ0aWxlSWQiOiJONiIsImd1aWQiOiI5ODBDMzIzOS00ODIyLUM5RTItMjAzQi1FMkMxOTgwOEZCMDEiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjAiLCJpY29uIjoidHJhZGluZ3Bvc3QiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjUiLCJpY29uIjoiZ29sZG1pbmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjAiLCJpY29uIjoibWFnaWNzcHJpbmciLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjQiLCJpY29uIjoicGFuZG9yYSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiJmb3VudGFpbi1vZi15b3V0aCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiJ3YXRlcndoZWVsIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoibGF2YSIsImdyb3VwIjoibmVhciIsImV4cGFuc2lvbiI6ImluZmVybm8iLCJ0aWxlSWQiOiJOMTIiLCJndWlkIjoiNEY0QzFFRjUtMTQ0MS04NTc2LUJBNEMtNzUyNDg3MkM1MDVEIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiI0IiwiaWNvbiI6Im15c3RpY2FsLWdhcmRlbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiJvYnNlcnZhdG9yeSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJ3YXRlcndoZWVsIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MywiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIwIiwiaWNvbiI6InRyYWRpbmdwb3N0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6ImNoZXN0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiI1IiwiaWNvbiI6ImdvbGRtaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoiY3Vyc2VkIiwiZ3JvdXAiOiJzdGFydGluZ3RpbGUiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiUzEiLCJndWlkIjoiMjg0QjkzQzYtRjkzQS02OTlGLTVBRjktQTQzMjI5ODk1MjlBIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMSIsImljb24iOiJvcmVwaXQiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoibmVjcm9wb2xpcyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiJjYW1wZmlyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOnRydWV9LHsiY2VsbCI6NSwiZW5lbXkiOiIxIiwiaWNvbiI6IndhZ29uIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX1dfSx7InRlcnJhaW4iOiJzdWJ0ZXJyYWluIiwiZ3JvdXAiOiJzdGFydGluZ3RpbGUiLCJleHBhbnNpb24iOiJjb3JlIiwidGlsZUlkIjoiUzIiLCJndWlkIjoiMDFFRDNGQjMtQTJDNC04MzI2LTI3RUYtRTJFQzlGNDU0MDYzIiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiJjYW1wZmlyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOnRydWV9LHsiY2VsbCI6MywiZW5lbXkiOiIwIiwiaWNvbiI6ImR1bmdlb24iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo0LCJlbmVteSI6IjEiLCJpY29uIjoib3JlcGl0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIxIiwiaWNvbiI6IndhZ29uIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX1dfSx7InRlcnJhaW4iOiJncmFzcyIsImdyb3VwIjoic3RhcnRpbmd0aWxlIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IlMzIiwiZ3VpZCI6IjhFNEVCRjBGLUZBMDEtREU0QS1BOTFELUFFRjNDNTc5QkZFOSIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjEiLCJpY29uIjoid2Fnb24iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoiY2FzdGxlIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIwIiwiaWNvbiI6ImNhbXBmaXJlIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX0seyJjZWxsIjo1LCJlbmVteSI6IjEiLCJpY29uIjoib3JlcGl0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX1dfSx7InRlcnJhaW4iOiJncmFzcyIsImdyb3VwIjoic3RhcnRpbmd0aWxlIiwiZXhwYW5zaW9uIjoicmFtcGFydCIsInRpbGVJZCI6IlM0IiwiZ3VpZCI6IkVENTZGRDU0LTRGOEMtQURBQS1DOEZFLUU2NDNFMkQwQTNEQiIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjp0cnVlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiJjYW1wZmlyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMSIsImljb24iOiJzYXdtaWxsIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoicmFtcGFydCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMSIsImljb24iOiJ3YWdvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOnRydWV9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6InN3YW1wIiwiZ3JvdXAiOiJzdGFydGluZ3RpbGUiLCJleHBhbnNpb24iOiJmb3J0cmVzcyIsInRpbGVJZCI6IlM1IiwiZ3VpZCI6IjA3NDhGQUZDLTkyREItRjE1MC1CRUI5LUJCRjkwRTE4NjgxRiIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMSIsImljb24iOiJ3YWdvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjp0cnVlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjMsImVuZW15IjoiMCIsImljb24iOiJmb3J0cmVzcyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiJjYW1wZmlyZSIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOnRydWV9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMSIsImljb24iOiJvcmVwaXQiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjp0cnVlfV19LHsidGVycmFpbiI6ImxhdmEiLCJncm91cCI6InN0YXJ0aW5ndGlsZSIsImV4cGFuc2lvbiI6ImluZmVybm8iLCJ0aWxlSWQiOiJTNiIsImd1aWQiOiJDRDgzRTZCRC05N0JFLTRERTEtOUU0My1BMjg5QzlEQ0NCNkUiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjAiLCJpY29uIjoiY2FtcGZpcmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjp0cnVlfSx7ImNlbGwiOjEsImVuZW15IjoiMSIsImljb24iOiJvcmVwaXQiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6dHJ1ZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoiaW5mZXJubyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMSIsImljb24iOiJ3YWdvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOnRydWV9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6InNub3ciLCJncm91cCI6ImZhciIsImV4cGFuc2lvbiI6InRvd2VyIiwidGlsZUlkIjoiI0YxIiwiZ3VpZCI6IjVEMzI4MzgxLTFDNjItQjAxNC03MDExLURBNkVFMTZGNzk3MSIsImRhdGEiOlt7ImNlbGwiOjAsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoid2luZG1pbGwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjMiLCJpY29uIjoicmFuZG9tLXRvd2VyIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MywiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIyIiwiaWNvbiI6ImNoZXN0IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6InN0YWJsZXMiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoid2l0Y2hodXQiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJzbm93IiwiZ3JvdXAiOiJmYXIiLCJleHBhbnNpb24iOiJ0b3dlciIsInRpbGVJZCI6IiNGMiIsImd1aWQiOiJGODU1NDFDNC05M0M2LTQ5RjgtMzk5Qy1CRjNFREU4Q0M5QzUiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjAiLCJpY29uIjoidHJhZGluZ3Bvc3QiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjIiLCJpY29uIjoic2tlbGV0b24iLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjAiLCJpY29uIjoiY2FtcGZpcmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIwIiwiaWNvbiI6ImxlYXJuaW5nLXN0b25lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIzIiwiaWNvbiI6ImdvbGRtaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoic25vdyIsImdyb3VwIjoiZmFyIiwiZXhwYW5zaW9uIjoidG93ZXIiLCJ0aWxlSWQiOiIjRjMiLCJndWlkIjoiRUVFMDY3RDktNTE2MS1ENTQ1LTQwRjUtNEU3MzI5OTI5NzM5IiwiZGF0YSI6W3siY2VsbCI6MCwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOnRydWUsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MSwiZW5lbXkiOiIwIiwiaWNvbiI6Im9ic2VydmF0b3J5IiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6MiwiZW5lbXkiOiIyIiwiaWNvbiI6Im15c3RpY2FsLWdhcmRlbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjMsImVuZW15IjoiMyIsImljb24iOiJnZW1wb25kIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NCwiZW5lbXkiOiIwIiwiaWNvbiI6Im1hZ2ljc2hyaW5lIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NSwiZW5lbXkiOiIwIiwiaWNvbiI6IiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjYsImVuZW15IjoiMCIsImljb24iOiJ3YXRlcndoZWVsIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9XX0seyJ0ZXJyYWluIjoic3VidGVycmFpbiIsImdyb3VwIjoiZmFyIiwiZXhwYW5zaW9uIjoiY29yZSIsInRpbGVJZCI6IiNGNSIsImd1aWQiOiIxNzhCNEUzMC03RjNDLUE2MTItNDE3MC0wOUQ0RTQzREI4MkYiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjAiLCJpY29uIjoiIiwiYmxvY2tlZCI6dHJ1ZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoidHJhZGluZ3Bvc3QiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjMiLCJpY29uIjoic2F3bWlsbCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjMsImVuZW15IjoiMCIsImljb24iOiJjaGVzdCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMiIsImljb24iOiJtYWdpY3NwcmluZyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiJ3YXRlcndoZWVsIiwiYmxvY2tlZCI6ZmFsc2UsImJvcmRlciI6ZmFsc2V9LHsiY2VsbCI6NiwiZW5lbXkiOiIwIiwiaWNvbiI6Im15c3RpY2FsLWdhcmRlbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfV19LHsidGVycmFpbiI6InNub3ciLCJncm91cCI6Im5lYXIiLCJleHBhbnNpb24iOiJ0b3dlciIsInRpbGVJZCI6IiNOMSIsImd1aWQiOiIyMDhBMDUzNy0zRkRELUFERTctM0YyMy0yMzJFNUI5NUQxMDciLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjQiLCJpY29uIjoidHJlZS1vZi1rbm93bGVkZ2UiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoxLCJlbmVteSI6IjAiLCJpY29uIjoibWFnaWNzcHJpbmciLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjoyLCJlbmVteSI6IjUiLCJpY29uIjoiZ29sZG1pbmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjozLCJlbmVteSI6IjAiLCJpY29uIjoic3RhYmxlcyIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjUsImVuZW15IjoiMCIsImljb24iOiJ0ZW1wbGUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo2LCJlbmVteSI6IjAiLCJpY29uIjoid2luZG1pbGwiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX1dfSx7InRlcnJhaW4iOiJzbm93IiwiZ3JvdXAiOiJzdGFydGluZ3RpbGUiLCJleHBhbnNpb24iOiJ0b3dlciIsInRpbGVJZCI6IiNTMSIsImd1aWQiOiJBNzdEQzc4Ny0wNDhELUFDRUUtNjA4NS01REU1RjI0RUIwN0IiLCJkYXRhIjpbeyJjZWxsIjowLCJlbmVteSI6IjEiLCJpY29uIjoic2F3bWlsbCIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjEsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjp0cnVlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjIsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjp0cnVlfSx7ImNlbGwiOjMsImVuZW15IjoiMCIsImljb24iOiJ0b3dlciIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOmZhbHNlfSx7ImNlbGwiOjQsImVuZW15IjoiMCIsImljb24iOiIiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjpmYWxzZX0seyJjZWxsIjo1LCJlbmVteSI6IjAiLCJpY29uIjoiY2FtcGZpcmUiLCJibG9ja2VkIjpmYWxzZSwiYm9yZGVyIjp0cnVlfSx7ImNlbGwiOjYsImVuZW15IjoiMSIsImljb24iOiJ3YWdvbiIsImJsb2NrZWQiOmZhbHNlLCJib3JkZXIiOnRydWV9XX1d';

  constructor() {
    this.load();
  }

  load() {
    const data = localStorage.getItem(this.storageKey);
    if (data) {
      this.tileList = JSON.parse(data);
    } else {
      this.init();
    }
  }

  updateTile(data: any) {
    const index = this.tileList.findIndex((tile) => {
      return tile.guid === data.guid;
    })
    this.tileList[index] = data;
    this.save();
  }

  deleteTile(guid: string) {
    if (!confirm("Are you sure you want to delete this tile?")) {
      return;
    }

    const index = this.tileList.findIndex((tile) => {
      return tile.guid === guid;
    })
    this.tileList.splice(index, 1);
    console.log('@', index, guid)
    this.save();
  }

  save(){
    localStorage.setItem(this.storageKey, JSON.stringify(this.tileList));
  }

  newTile() {
    const tile: StorageSaveData = {
      terrain: 'grass',
      group: 'far',
      expansion: 'core',
      tileId: '',
      guid: this.generateGuid(),
      data: this.getEmptyTileData()
    }

    this.tileList.unshift(tile);
  }

  init() {
    this.newTile();
    this.save();
  }

  getEmptyTileData(): SaveData[] {
    return [
      {
        cell: 0,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      },
      {
        cell: 1,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      },
      {
        cell: 2,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      },
      {
        cell: 3,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      },
      {
        cell: 4,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      },
      {
        cell: 5,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      },
      {
        cell: 6,
        enemy: '0',
        icon: '',
        blocked: false,
        border: false
      }]
  }

  private generateGuid():string {
    let result, i, j;
    result = '';
    for(j=0; j<32; j++) {
      if( j == 8 || j == 12 || j == 16 || j == 20)
        result = result + '-';
      i = Math.floor(Math.random()*16).toString(16).toUpperCase();
      result = result + i;
    }
    return result;
  }


  public download(dataurl: any, filename: string) {
    const link = document.createElement("a");
    link.href = dataurl;
    link.download = filename;
    link.click();
  }

  generate() {
    this.tileList.forEach((tile) => {
      let node:any = document.getElementById(tile.guid);
      htmlToImage.toPng(node)
        .then( (dataUrl) => {
          this.download(dataUrl, `${tile.tileId.replace("#", "_")}.png`)
        })
        .catch(function (error) {
          console.error('oops, something went wrong!', error);
        });
    })
  }

  sort() {
    const getStringValue = function(text: string) {
      const charList = text.replace(/[0-9]/g, '').split("");
      const number = text.replace(/\D/g, '');
      const res = charList.map((letter: string) => {
        if (/^\d+$/.test(letter)) {
          return parseInt(letter);
        }
        return letter.charCodeAt(0) * 100;
      }).reduce((acc: number, val: number) => {
        return acc + val
      }, 0) + parseInt(number);
      return res;
    }
    this.tileList.sort((tileA:StorageSaveData, tileB:StorageSaveData) => {
      return getStringValue(tileA.tileId) - getStringValue(tileB.tileId)
    })
    this.save();
  }

  export() {
    const generateBlockedList = (tile: any) => {
      const getBlockedFromCellData = (cellId: number) => {
        return tile.data[cellId].blocked || tile.data[cellId].border ? 1 : 0;
      }

      return [
        getBlockedFromCellData(1),
        getBlockedFromCellData(4),
        getBlockedFromCellData(6),
        getBlockedFromCellData(5),
        getBlockedFromCellData(2),
        getBlockedFromCellData(0)
      ]
    }
    const generateDesc = (tile: any) => {
      return tile.group.charAt(0).toUpperCase() + tile.group.slice(1) + " Tile " + tile.tileId
    }

    const result: any = {}
    this.tileList.map(tile => {
      const t = {
        id: tile.tileId,
        img: "assets/tiles/" + tile.tileId.replace("#", "_") + ".png",
        desc: generateDesc(tile),
        expansionID: "EXPANSION." + tile.expansion?.toUpperCase(),
        groundType: "GROUNDTYPE." + tile.terrain.toUpperCase(),
        group: "GROUP." + tile.group?.toUpperCase(),
        blocked: generateBlockedList(tile)
      }
      result[tile.tileId] = t;
    });

    this.exportImport = btoa(JSON.stringify(this.tileList));
  }

  import() {
    console.log(
      JSON.parse(
        atob(this.defaultData)
      )
    )
    this.tileList = JSON.parse(
      atob(this.defaultData)
    );
    this.save();
  }
}
