export enum SPECIALS {
  "IGNORE_RETALIATION",
  "IGNORE_COMBAT_PENALTY_ADJACENT",
  "IGNORE_PARALYSIS",// TODO
  "CHANCE_TO_PARALYZE_ON_RETALIATION", // TODO
  "PARALYZE_ON_RETALIATION", // TODO
  "IGNORE_DEFENCE",
  "IGNORE_DAMAGE_FROM_SPECIALS", // TODO but not yet needed
  "DOUBLE_ATTACK_NON_ADJACENT",
  "REROLL_ZERO_ON_DICE",
  "REROLL_ON_OTHER_SPACE",
}
