export enum SPECIALS {
  "IGNORE_RETALIATION",
  "IGNORE_COMBAT_PENALTY_ADJACENT",
  "IGNORE_COMBAT_PENALTY", // TODO
  "LUCK",
  "IGNORE_PARALYSIS",
  "CHANCE_TO_PARALYZE_ON_RETALIATION", // way to situational at the moment. perhaps set adjacency to false??
  "PARALYZE_ON_RETALIATION", // way to situational at the moment.perhaps set adjacency to false??
  "IGNORE_DEFENCE",
  "IGNORE_DAMAGE_FROM_SPECIALS_AND_MAGIC", // TODO but not yet needed
  "DOUBLE_ATTACK_NON_ADJACENT",
  "REROLL_ZERO_ON_DICE",
  "REROLL_ON_OTHER_SPACE",
  "DEFENCE_ON_ATTACK_ONE", // TODO
  "DEFENCE_ON_ATTACK_ZERO_ONE", // TODO
  "HEAL_ONE_ON_ACTIVATION",
  "HEAL_THREE_ON_ACTIVATION",
  "HEAL_TWO_ON_ATTACK",
  "RETALIATION_CURSE", // TODO
  "DEATH_BLOW",
  "ADD_ONE_TO_ATTACK_DICE",
  "FEAR",
  "NOT_ADJACENT_CHANCE_DOUBLE_ATTACK",
  "LOWER_RETALIATION_DAMAGE",
  "CHANCE_TO_PARALYZE_MINUS_ONE",
  "DEATH_STARE",
  "POISON",
  "MIGHTY_POISON",
  "RUST_ATTACK", // TODO
  "FAERIE_SPELL_ATTACK", // TODO MAKE SURE GOLEMS REDUCE THIS DAMAGE AND DRAGONS IGNORE IT
  "SPELL_REDUCTION_ONE", // TODO
  "SPELL_REDUCTION_TWO", // TODO
  "SPELL_REDUCTION_THREE", // TODO
  "NO_ROLL_FOR_ATTACK", // TODO
  "CURSE", // TODO
  "ENCHANTER",
}
