export enum SPECIALS {
  "IGNORE_RETALIATION",
  "IGNORE_COMBAT_PENALTY_ADJACENT",
  "IGNORE_PARALYSIS",
  "CHANCE_TO_PARALYZE_ON_RETALIATION", // way to situational at the moment. perhaps set adjacency to false??
  "PARALYZE_ON_RETALIATION", // way to situational at the moment.perhaps set adjacency to false??
  "IGNORE_DEFENCE",
  "IGNORE_DAMAGE_FROM_SPECIALS_AND_MAGIC", // TODO but not yet needed
  "DOUBLE_ATTACK_NON_ADJACENT",
  "REROLL_ZERO_ON_DICE",
  "REROLL_ON_OTHER_SPACE",
  "DEFENCE_ON_ATTACK_ONE", // TODO
  "DEFENCE_ON_ATTACK_ZERO_ONE", // TODO
  "HEAL_ONE_ON_ACTIVATION",
  "HEAL_TWO_ON_ATTACK",
  "CURSE_AFTER_ATTACK", // TODO
  "DEATH_BLOW", // TODO
  "STRONGER_ATTACK_DICE", // TODO
  "FEAR",
  "NOT_ADJACENT_CHANCE_DOUBLE_ATTACK",// TODO
  "LOWER_RETALIATION_DAMAGE",
  "CHANCE_TO_PARALYZE_MINUS_ONE",// TODO
  "DEATH_STARE",
  "POISON",// TODO
  "MIGHTY_POISON",// TODO
}
